/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sfg.ilu4.ihm.tp1;

import javax.swing.JDialog;

/**
 *
 * @author FRS4440A
 */
public class Exercice2 extends javax.swing.JFrame {

    /**
     * Creates new form Exercice2
     */
    public Exercice2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogFileChooser = new javax.swing.JDialog();
        jFileChooserFichierImprimer = new javax.swing.JFileChooser();
        jPanelFichierImprimer = new javax.swing.JPanel();
        jLabelNomFichier = new javax.swing.JLabel();
        jTextFieldNom = new javax.swing.JTextField();
        jButtonParcourir = new javax.swing.JButton();
        jPanelOptionImpression = new javax.swing.JPanel();
        jPanelOptionImpressionGauche = new javax.swing.JPanel();
        jLabelNbCopies = new javax.swing.JLabel();
        jSpinnerNbCopies = new javax.swing.JSpinner();
        jLabelFormat = new javax.swing.JLabel();
        jComboBoxFormat = new javax.swing.JComboBox<>();
        jCheckBoxRecto = new javax.swing.JCheckBox();
        jPanelOptionImpressionDroite = new javax.swing.JPanel();
        jRadioButtonNoir = new javax.swing.JRadioButton();
        jRadioButtonCouleur = new javax.swing.JRadioButton();
        jLabelQualite = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelImpressionsPlanifiees = new javax.swing.JPanel();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaImpressionPlanifiees = new javax.swing.JTextArea();
        jPanelPrixImpression = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPrixImpressionPlanifiees = new javax.swing.JTextArea();

        jDialogFileChooser.setMinimumSize(new java.awt.Dimension(598, 347));

        jFileChooserFichierImprimer.setDialogTitle("Veuillez chosiir un fichier à imprimer");
        jFileChooserFichierImprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserFichierImprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogFileChooserLayout = new javax.swing.GroupLayout(jDialogFileChooser.getContentPane());
        jDialogFileChooser.getContentPane().setLayout(jDialogFileChooserLayout);
        jDialogFileChooserLayout.setHorizontalGroup(
            jDialogFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogFileChooserLayout.createSequentialGroup()
                .addComponent(jFileChooserFichierImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialogFileChooserLayout.setVerticalGroup(
            jDialogFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogFileChooserLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jFileChooserFichierImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion impressions");

        jPanelFichierImprimer.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fichier à imprimer"));

        jLabelNomFichier.setText("Nom du fichier :");

        jTextFieldNom.setEditable(false);
        jTextFieldNom.setFocusable(false);

        jButtonParcourir.setText("Parcourir...");
        jButtonParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcourirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFichierImprimerLayout = new javax.swing.GroupLayout(jPanelFichierImprimer);
        jPanelFichierImprimer.setLayout(jPanelFichierImprimerLayout);
        jPanelFichierImprimerLayout.setHorizontalGroup(
            jPanelFichierImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichierImprimerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomFichier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonParcourir)
                .addContainerGap())
        );
        jPanelFichierImprimerLayout.setVerticalGroup(
            jPanelFichierImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFichierImprimerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelNomFichier)
                .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonParcourir))
        );

        jPanelOptionImpression.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Options d'impression"));

        jPanelOptionImpressionGauche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelNbCopies.setText("Nb de copies");

        jSpinnerNbCopies.setPreferredSize(new java.awt.Dimension(70, 25));

        jLabelFormat.setText("Format");

        jComboBoxFormat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A3", "A4", "A5", "A6" }));

        jCheckBoxRecto.setText("Recto/Verso");

        javax.swing.GroupLayout jPanelOptionImpressionGaucheLayout = new javax.swing.GroupLayout(jPanelOptionImpressionGauche);
        jPanelOptionImpressionGauche.setLayout(jPanelOptionImpressionGaucheLayout);
        jPanelOptionImpressionGaucheLayout.setHorizontalGroup(
            jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionImpressionGaucheLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxRecto)
                    .addGroup(jPanelOptionImpressionGaucheLayout.createSequentialGroup()
                        .addGroup(jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNbCopies)
                            .addComponent(jLabelFormat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxFormat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerNbCopies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelOptionImpressionGaucheLayout.setVerticalGroup(
            jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionImpressionGaucheLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbCopies)
                    .addComponent(jSpinnerNbCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOptionImpressionGaucheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFormat)
                    .addComponent(jComboBoxFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBoxRecto)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelOptionImpressionDroite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jRadioButtonNoir.setText("Noir et Blanc");
        jRadioButtonNoir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoirActionPerformed(evt);
            }
        });

        jRadioButtonCouleur.setText("Couleur");
        jRadioButtonCouleur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCouleurActionPerformed(evt);
            }
        });

        jLabelQualite.setText("Qualité du papier");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economique", "Photo", "Glacé" }));

        javax.swing.GroupLayout jPanelOptionImpressionDroiteLayout = new javax.swing.GroupLayout(jPanelOptionImpressionDroite);
        jPanelOptionImpressionDroite.setLayout(jPanelOptionImpressionDroiteLayout);
        jPanelOptionImpressionDroiteLayout.setHorizontalGroup(
            jPanelOptionImpressionDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionImpressionDroiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionImpressionDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButtonNoir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButtonCouleur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelQualite, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOptionImpressionDroiteLayout.setVerticalGroup(
            jPanelOptionImpressionDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionImpressionDroiteLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jRadioButtonNoir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCouleur)
                .addGap(12, 12, 12)
                .addGroup(jPanelOptionImpressionDroiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQualite, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelOptionImpressionLayout = new javax.swing.GroupLayout(jPanelOptionImpression);
        jPanelOptionImpression.setLayout(jPanelOptionImpressionLayout);
        jPanelOptionImpressionLayout.setHorizontalGroup(
            jPanelOptionImpressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionImpressionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOptionImpressionGauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOptionImpressionDroite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelOptionImpressionLayout.setVerticalGroup(
            jPanelOptionImpressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionImpressionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOptionImpressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelOptionImpressionGauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOptionImpressionDroite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelImpressionsPlanifiees.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Impressions planifiées"));

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jTextAreaImpressionPlanifiees.setEditable(false);
        jTextAreaImpressionPlanifiees.setColumns(20);
        jTextAreaImpressionPlanifiees.setRows(5);
        jTextAreaImpressionPlanifiees.setFocusable(false);
        jScrollPane1.setViewportView(jTextAreaImpressionPlanifiees);

        javax.swing.GroupLayout jPanelImpressionsPlanifieesLayout = new javax.swing.GroupLayout(jPanelImpressionsPlanifiees);
        jPanelImpressionsPlanifiees.setLayout(jPanelImpressionsPlanifieesLayout);
        jPanelImpressionsPlanifieesLayout.setHorizontalGroup(
            jPanelImpressionsPlanifieesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImpressionsPlanifieesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAjouter)
                .addGap(18, 18, 18)
                .addComponent(jButtonModifier)
                .addGap(18, 18, 18)
                .addComponent(jButtonSupprimer)
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImpressionsPlanifieesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelImpressionsPlanifieesLayout.setVerticalGroup(
            jPanelImpressionsPlanifieesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImpressionsPlanifieesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelImpressionsPlanifieesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelPrixImpression.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Prix des impressions planifiées"));

        jTextAreaPrixImpressionPlanifiees.setEditable(false);
        jTextAreaPrixImpressionPlanifiees.setColumns(20);
        jTextAreaPrixImpressionPlanifiees.setRows(5);
        jTextAreaPrixImpressionPlanifiees.setFocusable(false);
        jScrollPane2.setViewportView(jTextAreaPrixImpressionPlanifiees);

        javax.swing.GroupLayout jPanelPrixImpressionLayout = new javax.swing.GroupLayout(jPanelPrixImpression);
        jPanelPrixImpression.setLayout(jPanelPrixImpressionLayout);
        jPanelPrixImpressionLayout.setHorizontalGroup(
            jPanelPrixImpressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrixImpressionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanelPrixImpressionLayout.setVerticalGroup(
            jPanelPrixImpressionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrixImpressionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFichierImprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelOptionImpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelImpressionsPlanifiees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrixImpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFichierImprimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelOptionImpression, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelImpressionsPlanifiees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrixImpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jButtonParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcourirActionPerformed
        jDialogFileChooser.setVisible(true);
    }//GEN-LAST:event_jButtonParcourirActionPerformed

    private void jFileChooserFichierImprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserFichierImprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooserFichierImprimerActionPerformed

    private void jRadioButtonNoirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoirActionPerformed
        if (jRadioButtonCouleur.isSelected()){
            jRadioButtonCouleur.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonNoirActionPerformed

    private void jRadioButtonCouleurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCouleurActionPerformed
        if (jRadioButtonNoir.isSelected()){
            jRadioButtonNoir.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonCouleurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonParcourir;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JCheckBox jCheckBoxRecto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxFormat;
    private javax.swing.JDialog jDialogFileChooser;
    private javax.swing.JFileChooser jFileChooserFichierImprimer;
    private javax.swing.JLabel jLabelFormat;
    private javax.swing.JLabel jLabelNbCopies;
    private javax.swing.JLabel jLabelNomFichier;
    private javax.swing.JLabel jLabelQualite;
    private javax.swing.JPanel jPanelFichierImprimer;
    private javax.swing.JPanel jPanelImpressionsPlanifiees;
    private javax.swing.JPanel jPanelOptionImpression;
    private javax.swing.JPanel jPanelOptionImpressionDroite;
    private javax.swing.JPanel jPanelOptionImpressionGauche;
    private javax.swing.JPanel jPanelPrixImpression;
    private javax.swing.JRadioButton jRadioButtonCouleur;
    private javax.swing.JRadioButton jRadioButtonNoir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerNbCopies;
    private javax.swing.JTextArea jTextAreaImpressionPlanifiees;
    private javax.swing.JTextArea jTextAreaPrixImpressionPlanifiees;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
