/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sfg.ilu4.ihm.tp1;

/**
 *
 * @author FRS4440A
 */
public class Exercice1 extends javax.swing.JFrame {

    /**
     * Creates new form Exercice1
     */
    public Exercice1() {
        initComponents();
    }
    String texte="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jCheckBoxCase1 = new javax.swing.JCheckBox();
        jCheckBoxCase2 = new javax.swing.JCheckBox();
        jTextFieldSaisie = new javax.swing.JTextField();
        jLabelSaisie = new javax.swing.JLabel();
        jButtonBouton1 = new javax.swing.JButton();
        jButtonBouton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListe = new javax.swing.JList<>();
        jLabelListe = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservation = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Observation d'évènements");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null), "Test des actions utilisateur"));

        jCheckBoxCase1.setText("Case numéro 1");
        jCheckBoxCase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCase1ActionPerformed(evt);
            }
        });

        jCheckBoxCase2.setText("Case numéro 2");
        jCheckBoxCase2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCase2ActionPerformed(evt);
            }
        });

        jTextFieldSaisie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldSaisieFocusGained(evt);
            }
        });
        jTextFieldSaisie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSaisieKeyTyped(evt);
            }
        });

        jLabelSaisie.setText("Zone de saisie de texte :");

        jButtonBouton1.setText("Bouton 1");
        jButtonBouton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBouton1MouseClicked(evt);
            }
        });
        jButtonBouton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBouton1ActionPerformed(evt);
            }
        });

        jButtonBouton2.setText("Bouton 2");
        jButtonBouton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBouton2MouseClicked(evt);
            }
        });
        jButtonBouton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBouton2ActionPerformed(evt);
            }
        });

        jListListe.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item 8", "Item 9" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListListe.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListListe.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListListeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListListe);

        jLabelListe.setText("Liste :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSaisie)
                    .addComponent(jCheckBoxCase2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonBouton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBouton2))
                        .addComponent(jTextFieldSaisie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBoxCase1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelListe))
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckBoxCase1)
                    .addComponent(jLabelListe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBoxCase2)
                        .addGap(19, 19, 19)
                        .addComponent(jLabelSaisie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSaisie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBouton1)
                            .addComponent(jButtonBouton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jTextAreaObservation.setEditable(false);
        jTextAreaObservation.setColumns(20);
        jTextAreaObservation.setRows(5);
        jTextAreaObservation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(null), "Observation des évènements"));
        jTextAreaObservation.setFocusable(false);
        jScrollPane2.setViewportView(jTextAreaObservation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonReset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBouton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBouton1MouseClicked
        jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de cliquer sur le Bouton 1");
    }//GEN-LAST:event_jButtonBouton1MouseClicked

    private void jButtonBouton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBouton2MouseClicked
        jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de cliquer sur le Bouton 2");
    }//GEN-LAST:event_jButtonBouton2MouseClicked

    private void jListListeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListListeValueChanged
        if (evt.getValueIsAdjusting()==false){
            jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de sélectionner "+(jListListe.getSelectedValue())+" dans la liste");
        }
    }//GEN-LAST:event_jListListeValueChanged

    private void jButtonBouton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBouton1ActionPerformed
        jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez d'enfoncer le Bouton 1");
    }//GEN-LAST:event_jButtonBouton1ActionPerformed

    private void jTextFieldSaisieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldSaisieFocusGained
        jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de déplacer le curseur dans la zone de saisie de texte");
    }//GEN-LAST:event_jTextFieldSaisieFocusGained

    private void jTextFieldSaisieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSaisieKeyTyped
        jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de taper la touche "+evt.getKeyChar()+" dans la zone de saisie de texte");
    }//GEN-LAST:event_jTextFieldSaisieKeyTyped

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextAreaObservation.setText("");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonBouton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBouton2ActionPerformed
        jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez d'enfoncer le Bouton 2");
    }//GEN-LAST:event_jButtonBouton2ActionPerformed

    private void jCheckBoxCase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCase1ActionPerformed
        if (jCheckBoxCase1.isSelected()){
           jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de cocher la Case numéro 1");
        }else{
            jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de décocher la Case numéro 1");
        }
    }//GEN-LAST:event_jCheckBoxCase1ActionPerformed

    private void jCheckBoxCase2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCase2ActionPerformed
        if (jCheckBoxCase2.isSelected()){
           jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de cocher la Case numéro 2");
        }else{
            jTextAreaObservation.setText(jTextAreaObservation.getText()+"\n"+"Vous venez de décocher la Case numéro 2");
        }
    }//GEN-LAST:event_jCheckBoxCase2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercice1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercice1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBouton1;
    private javax.swing.JButton jButtonBouton2;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JCheckBox jCheckBoxCase1;
    private javax.swing.JCheckBox jCheckBoxCase2;
    private javax.swing.JLabel jLabelListe;
    private javax.swing.JLabel jLabelSaisie;
    private javax.swing.JList<String> jListListe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaObservation;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldSaisie;
    // End of variables declaration//GEN-END:variables
}
